package com.mycompany.webapp.dto;

import java.text.SimpleDateFormat;
import java.util.Date;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class MailData {
	public String ip;
	public MailData(String ip) {
		this.ip = ip;
	}
	public String getToday() {
		Date date = new Date();
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return format.format(date);
	}
	public String getMailText1(String ip) {
		log.info("ip = " + ip);
		String mailText1 = "<b>Asdasd</b> <a href='http://google.con'> google</a>";
		return mailText1;
	}
	
//	public String getMailText2(String ip) {
//			String mailText2 =  
//			"                              <tr>\r\n"
//			+ "                                <td colspan=\"2\"\r\n"
//			+ "                                  style=\"padding-top:15px;line-height:0;border-top:1px dotted #e6e6e6;font-size:11px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:15px\">\r\n"
//			+ "                                  HYUNDAI X TEAM2 | 사업자명 : 편지회형은솔 | <br>\r\n"
//			+ "                                  대표자명 : 편지 대표전화 : 010-1234-5678 | 대표주소 : (02203) 서울특별시 송파구 중대로 135 서관 12층 L1\r\n"
//			+ "\r\n"
//			+ "                                  <br>판매자 특이사항: 특이사항 없음\r\n"
//			+ "                                </td>\r\n"
//			+ "                              </tr>\r\n"
//			+ "                              <tr>\r\n"
//			+ "                                <td colspan=\"2\" height=\"17\"></td>\r\n"
//			+ "                              </tr>\r\n"
//			+ "                            </tbody>\r\n"
//			+ "                          </table>\r\n"
//			+ "                        </td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                    </tbody>\r\n"
//			+ "                  </table>\r\n"
//			+ "                </td>\r\n"
//			+ "                <td width=\"21\"></td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <!--// 주문상품 -->\r\n"
//			+ "\r\n"
//			+ "              <!-- 최종결제 금액 -->\r\n"
//			+ "\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td width=\"21\"></td>\r\n"
//			+ "                <td>\r\n"
//			+ "                  <table cellpadding=\"0\" cellspacing=\"0\" style=\"width:100%;margin:0;padding:0\">\r\n"
//			+ "                    <tbody>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"1\" style=\"height:2px;background:#424240\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"17\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td width=\"50%\"\r\n"
//			+ "                          style=\"padding-bottom:12px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:16px;vertical-align:top\">\r\n"
//			+ "                          상품금액\r\n"
//			+ "                        </td>\r\n"
//			+ "                        <td\r\n"
//			+ "                          style=\"padding-bottom:12px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#000;line-height:16px;text-align:right;vertical-align:top\">\r\n"
//			+ "                          <span style=\"font-family:Helvetica;line-height:20px\"></span>원\r\n"
//			+ "                        </td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td width=\"50%\"\r\n"
//			+ "                          style=\"padding-bottom:12px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:16px;vertical-align:top\">\r\n"
//			+ "                          배송비\r\n"
//			+ "                        </td>\r\n"
//			+ "                        <td\r\n"
//			+ "                          style=\"padding-bottom:12px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#000;line-height:16px;text-align:right;vertical-align:top\">\r\n"
//			+ "                          <span style=\"font-family:Helvetica;line-height:20px\">\r\n"
//			+ "                            0\r\n"
//			+ "                          </span>원\r\n"
//			+ "                        </td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td width=\"50%\"\r\n"
//			+ "                          style=\"padding-bottom:18px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:16px;vertical-align:top\">\r\n"
//			+ "                          마일리지\r\n"
//			+ "                        </td>\r\n"
//			+ "                        <td\r\n"
//			+ "                          style=\"padding-bottom:18px;font-size:14px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#000;line-height:16px;text-align:right;vertical-align:top\">\r\n"
//			+ "                          <span style=\"font-family:Helvetica;line-height:20px\">\r\n"
//			+ "                            \r\n"
//			+ "                          </span>원\r\n"
//			+ "                        </td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"17\" style=\"border-top: 1px dotted #e6e6e6;\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td width=\"45%\"\r\n"
//			+ "                          style=\"font-size:16px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;font-weight:bold;color:#333;line-height:22px\">\r\n"
//			+ "                          주문금액\r\n"
//			+ "                        </td>\r\n"
//			+ "                        <td\r\n"
//			+ "                          style=\"font-size:16px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;font-weight:bold;color:#333;text-align:right;line-height:30px\">\r\n"
//			+ "                          <span\r\n"
//			+ "                            style=\"font-size:30px;font-family:HelveticaNeue;color:#959ace;vertical-align:top\"></span>원\r\n"
//			+ "                        </td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"17\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"1\" style=\"background:#424240\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                      <tr>\r\n"
//			+ "                        <td colspan=\"2\" height=\"29\"></td>\r\n"
//			+ "                      </tr>\r\n"
//			+ "                    </tbody>\r\n"
//			+ "                  </table>\r\n"
//			+ "                </td>\r\n"
//			+ "                <td width=\"21\"></td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <!--// 최종결제 금액 -->\r\n"
//			+ "\r\n"
//			+ "\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td align=\"center\" colspan=\"3\">\r\n"
//			+ "                  <div style=\"display:inline-block;width:278px;max-width:100%;vertical-align:top\">\r\n"
//			+"                    <table style=\"table-layout: fixed;width:100%;background:#000051\" border=\"0\" cellpadding=\"0\"\r\n"
//			+ "                      cellspacing=\"0\">\r\n"
//			+ "                      <tbody>\r\n"
//			+ "                        <tr>\r\n"
//			+ "                          <td height=\"56\" style=\"text-align:center\">\r\n"
//			+ "                            <a\r\n"
//			+ "                              style=\"display:block;:56px;font-size:18px;color:#fff;text-decoration:none;line-:56px;font-family:'나눔고딕', nanumgothic, '맑은고딕', malgun gothic, '돋움', dotum, helvetica, 'apple sd gothic neo', sans-serif; font-weight:bold\"\r\n"
//			+ "                              rel=\"noreferrer noopener\" target=\"_blank\">TEAM2 - 현지 은솔 회형</a>\r\n"
//			+ "                          </td>\r\n"
//			+ "                        </tr>\r\n"
//			+ "                      </tbody>\r\n"
//			+ "                    </table>"
//			+ "                  </div>\r\n"
//			+ "                </td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td colspan=\"3\" height=\"40\"></td>\r\n"
//			+ "              </tr>\r\n"
//			+ "\r\n"
//			+ "              <!-- footer-->\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td colspan=\"3\"\r\n"
//			+ "                  style=\"padding-top:26px;padding-left:21px;padding-right:21px;padding-bottom:13px;background:#e5e5e5;font-size:12px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:17px\">\r\n"
//			+ "                  본 메일은 발신전용입니다.<br>\r\n"
//			+ "                  상품의 배송/반품/교환/취소/환불 문의는 판매자에게 문의하시면 더 빠르고 정확한 처리가 가능합니다.<br>\r\n"
//			+ "\r\n"
//			+ "                </td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td colspan=\"3\"\r\n"
//			+ "                  style=\"padding-top:10px;padding-left:21px;padding-right:21px;padding-bottom:13px;background:#e5e5e5;font-size:12px;font-family:'나눔고딕',NanumGothic,'맑은고딕',Malgun Gothic,'돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;color:#696969;line-height:17px\">\r\n"
//			+ "                  <a href=\"http://pay.naver.com/provision\" style=\"padding-right:10px;color:#696969;text-decoration:none\"\r\n"
//			+ "                    rel=\"noreferrer noopener\" target=\"_blank\">이용약관</a> l <a\r\n"
//			+ "                    href=\"http://order.pay.naver.com/static/files/naverpay.docx\"\r\n"
//			+ "                    style=\"padding:0 10px;color:#696969;text-decoration:none\" rel=\"noreferrer noopener\"\r\n"
//			+ "                    target=\"_blank\">청약철회 등에 관한 사항</a> l <a href=\"http://pay.naver.com/policy/financial\"\r\n"
//			+ "                    style=\"padding:0 10px;color:#696969;text-decoration:none\" rel=\"noreferrer noopener\"\r\n"
//			+ "                    target=\"_blank\">개인정보 처리방침</a>\r\n"
//			+ "                </td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <tr>\r\n"
//			+ "                <td colspan=\"3\"\r\n"
//			+ "                  style=\"padding-left:21px;padding-right:21px;padding-bottom:57px;background:#e5e5e5;font-size:12px;font-family:Helvetica;color:#696969;line-height:17px\">\r\n"
//			+ "                  Copyright ⓒ <strong>Hyundai X TEAM2</strong> All Rights Reserved.\r\n"
//			+ "                </td>\r\n"
//			+ "              </tr>\r\n"
//			+ "              <!--// footer-->\r\n"
//			+ "\r\n"
//			+ "            </tbody>\r\n"
//			+ "          </table>\r\n"
//			+ "        </div>\r\n"
//			+ "        <!--[if mso]>\r\n"
//			+ "      </td></tr>\r\n"
//			+ "  </table>\r\n"
//			+ "<![endif]-->\r\n"
//			+ "\r\n"
//			+ "\r\n"
//			+ "      </td>\r\n"
//			+ "    </tr>\r\n"
//			+ "  </tbody>\r\n"
//			+ "</table>\r\n"
//			+ "</body>\r\n"
//			+ "</html>";
//			return mailText2;
//	}
			
			public String mailContent() {
				log.info("ip" + ip);
				return getMailText1(ip);
			}
}